# Generated by Django 5.1.7 on 2025-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
