# Generated by Django 5.1.7 on 2025-03-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0003_auto_20250319_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
