# Generated by Django 5.1.7 on 2025-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0004_alter_user_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                help_text="Token used for verification", max_length=64
            ),
        ),
    ]
