# Generated by Django 5.1.7 on 2025-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0006_alter_user_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                default="2203c0e31a2e4df5b01d4636795be41d", max_length=64, unique=True
            ),
        ),
    ]
