# Generated by Django 5.1.7 on 2025-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0007_alter_user_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                default="2d08d98631dc4869822bd8f61d84fd7f", max_length=64, unique=True
            ),
        ),
    ]
