# Generated by Django 5.1.7 on 2025-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0008_alter_user_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                default="bf1d80acf0e146f292ea2c0d8095e275", max_length=64, unique=True
            ),
        ),
    ]
