# Generated by Django 5.1.7 on 2025-03-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0010_alter_user_verification_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="otp_code",
            new_name="otp",
        ),
    ]
