# Generated by Django 5.1.7 on 2025-04-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global_neighbor", "0011_rename_otp_code_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("neighbor", "Neighbor"),
                    ("creator", "Creator"),
                    ("moderator", "Moderator"),
                ],
                default="neighbor",
                max_length=10,
            ),
        ),
    ]
