# Generated by Django 5.1.7 on 2025-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhood", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forumcategory",
            name="name",
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="title",
            field=models.CharField(default="General", max_length=200),
            preserve_default=False,
        ),
    ]
