# Generated by Django 5.1.7 on 2025-03-24 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "neighborhood",
            "0002_remove_forumcategory_name_forumcategory_description_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="ForumPost",
        ),
    ]
