# Generated by Django 5.1.7 on 2025-04-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborhood", "0004_forumpost_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumcategory",
            options={"ordering": ["sort_order", "title"]},
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="neighborhood.forumcategory",
            ),
        ),
        migrations.AddField(
            model_name="forumcategory",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
